//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcingaBusylightAgent {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IcingaBusylightAgent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are X hosts and Y services in faulty state... ähnelt.
        /// </summary>
        internal static string balloon_chaos_msg {
            get {
                return ResourceManager.GetString("balloon_chaos_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the shit hits the fan... ähnelt.
        /// </summary>
        internal static string balloon_chaos_title {
            get {
                return ResourceManager.GetString("balloon_chaos_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute(s) ähnelt.
        /// </summary>
        internal static string lbl_minutes {
            get {
                return ResourceManager.GetString("lbl_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console (default) ähnelt.
        /// </summary>
        internal static string logger_console {
            get {
                return ResourceManager.GetString("logger_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 50 stacks of trace ähnelt.
        /// </summary>
        internal static string logger_debug {
            get {
                return ResourceManager.GetString("logger_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors ähnelt.
        /// </summary>
        internal static string logger_error {
            get {
                return ResourceManager.GetString("logger_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EventLog ähnelt.
        /// </summary>
        internal static string logger_eventlog {
            get {
                return ResourceManager.GetString("logger_eventlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string logger_file {
            get {
                return ResourceManager.GetString("logger_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string logger_info {
            get {
                return ResourceManager.GetString("logger_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About... ähnelt.
        /// </summary>
        internal static string mnu_about {
            get {
                return ResourceManager.GetString("mnu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure ähnelt.
        /// </summary>
        internal static string mnu_configure {
            get {
                return ResourceManager.GetString("mnu_configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string mnu_exit {
            get {
                return ResourceManager.GetString("mnu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string mnu_update {
            get {
                return ResourceManager.GetString("mnu_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last update: ähnelt.
        /// </summary>
        internal static string mnu_update_last {
            get {
                return ResourceManager.GetString("mnu_update_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die processing... ähnelt.
        /// </summary>
        internal static string mnu_update_progress {
            get {
                return ResourceManager.GetString("mnu_update_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string msgbox_error {
            get {
                return ResourceManager.GetString("msgbox_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to write to EventLog, check permissions! ähnelt.
        /// </summary>
        internal static string msgbox_eventlog_unavailable {
            get {
                return ResourceManager.GetString("msgbox_eventlog_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to connect to Icinga2 instance, check settings! ähnelt.
        /// </summary>
        internal static string msgbox_icinga_unavailable {
            get {
                return ResourceManager.GetString("msgbox_icinga_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Aktualisierung läuft bereits! ähnelt.
        /// </summary>
        internal static string msgbox_update_running {
            get {
                return ResourceManager.GetString("msgbox_update_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ok ähnelt.
        /// </summary>
        internal static string state_0 {
            get {
                return ResourceManager.GetString("state_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die warning ähnelt.
        /// </summary>
        internal static string state_1 {
            get {
                return ResourceManager.GetString("state_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die critical ähnelt.
        /// </summary>
        internal static string state_2 {
            get {
                return ResourceManager.GetString("state_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unknown ähnelt.
        /// </summary>
        internal static string state_3 {
            get {
                return ResourceManager.GetString("state_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die auf ähnelt.
        /// </summary>
        internal static string state_on {
            get {
                return ResourceManager.GetString("state_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is active ähnelt.
        /// </summary>
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome ähnelt.
        /// </summary>
        internal static string welcome_title {
            get {
                return ResourceManager.GetString("welcome_title", resourceCulture);
            }
        }
    }
}
